# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8289d6e058c2efc64f8dce809b6e4d1ecb0410560cebe8d342bcf5b37885b16f6d52a3a15208a779264d55fc7e947fccde222913a4133c4a469c103cbb17d37c

test:
  secret_key_base: 02e8da742159261c7ab8cedbe9d232f9b49f90922d235ac4312803e3d12bea81e2cd544379101d28947c7ed8939184d1ac07691be01e0418df54951876d28e73

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
